logging:
  level:
    root: INFO
    org:
      apache:
        tomcat: ERROR
        catalina: ERROR
      springframework:
        context.support: WARN
        data: ERROR
        web: ERROR
      hibernate: ERROR
    com:
      cloud:
        microservicemongo: TRACE
  file:
    name: logs/application-debug.log

spring:
  output:
    ansi:
      enabled: ALWAYS

  data:
    mongodb:
#      authentication-database: admin
      uri: mongodb+srv://admin:admin@cluster0.znh2e.mongodb.net/microservices?retryWrites=true&w=majority
#      uri: mongodb://admin:admin@localhost:27017/microservices?authSource=admin

#      username: admin
#      password: admin
#      host: localhost
#      port: 27017
#      database: microservices




